### ISSUE TITLE
Coveralls broken on 1.4.0

### ISSUE THREAD

**Issue by chrisballinger** [nakiostudio/xcov#116]
I'm guessing the report format changed?

```
bundler: failed to load command: fastlane (/Users/chrisbal/.gem/ruby/2.4.0/bin/fastlane)
NoMethodError: [!] undefined method `each' for nil:NilClass
  /Users/chrisbal/.gem/ruby/2.4.0/gems/xcov-1.4.0/lib/xcov/coveralls_handler.rb:30:in `block (2 levels) in convert_and_store_coveralls_json'
  /Users/chrisbal/.gem/ruby/2.4.0/gems/xcov-1.4.0/lib/xcov/coveralls_handler.rb:25:in `each'
  /Users/chrisbal/.gem/ruby/2.4.0/gems/xcov-1.4.0/lib/xcov/coveralls_handler.rb:25:in `block in convert_and_store_coveralls_json'
  /Users/chrisbal/.gem/ruby/2.4.0/gems/xcov-1.4.0/lib/xcov/coveralls_handler.rb:23:in `each'
  /Users/chrisbal/.gem/ruby/2.4.0/gems/xcov-1.4.0/lib/xcov/coveralls_handler.rb:23:in `convert_and_store_coveralls_json'
  /Users/chrisbal/.gem/ruby/2.4.0/gems/xcov-1.4.0/lib/xcov/coveralls_handler.rb:10:in `submit'
  /Users/chrisbal/.gem/ruby/2.4.0/gems/xcov-1.4.0/lib/xcov/manager.rb:136:in `submit_to_coveralls'
  /Users/chrisbal/.gem/ruby/2.4.0/gems/xcov-1.4.0/lib/xcov/manager.rb:33:in `run'
  /Users/chrisbal/.gem/ruby/2.4.0/gems/fastlane-2.89.0/fastlane/lib/fastlane/actions/xcov.rb:8:in `run'
  /Users/chrisbal/.gem/ruby/2.4.0/gems/fastlane-2.89.0/fastlane/lib/fastlane/runner.rb:257:in `block (2 levels) in execute_action'
  /Users/chrisbal/.gem/ruby/2.4.0/gems/fastlane-2.89.0/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
  /Users/chrisbal/.gem/ruby/2.4.0/gems/fastlane-2.89.0/fastlane/lib/fastlane/runner.rb:236:in `block in execute_action'
  /Users/chrisbal/.gem/ruby/2.4.0/gems/fastlane-2.89.0/fastlane/lib/fastlane/runner.rb:231:in `chdir'
  /Users/chrisbal/.gem/ruby/2.4.0/gems/fastlane-2.89.0/fastlane/lib/fastlane/runner.rb:231:in `execute_action'
  /Users/chrisbal/.gem/ruby/2.4.0/gems/fastlane-2.89.0/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
  /Users/chrisbal/.gem/ruby/2.4.0/gems/fastlane-2.89.0/fastlane/lib/fastlane/fast_file.rb:148:in `method_missing'
  Fastfile:51:in `block (2 levels) in parsing_binding'
  /Users/chrisbal/.gem/ruby/2.4.0/gems/fastlane-2.89.0/fastlane/lib/fastlane/lane.rb:33:in `call'
  /Users/chrisbal/.gem/ruby/2.4.0/gems/fastlane-2.89.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
  /Users/chrisbal/.gem/ruby/2.4.0/gems/fastlane-2.89.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
  /Users/chrisbal/.gem/ruby/2.4.0/gems/fastlane-2.89.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
  /Users/chrisbal/.gem/ruby/2.4.0/gems/fastlane-2.89.0/fastlane/lib/fastlane/lane_manager.rb:57:in `cruise_lane'
  /Users/chrisbal/.gem/ruby/2.4.0/gems/fastlane-2.89.0/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
  /Users/chrisbal/.gem/ruby/2.4.0/gems/fastlane-2.89.0/fastlane/lib/fastlane/commands_generator.rb:108:in `block (2 levels) in run'
  /Users/chrisbal/.gem/ruby/2.4.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
  /Users/chrisbal/.gem/ruby/2.4.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
  /Users/chrisbal/.gem/ruby/2.4.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
  /Users/chrisbal/.gem/ruby/2.4.0/gems/fastlane-2.89.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:75:in `run!'
  /Users/chrisbal/.gem/ruby/2.4.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
  /Users/chrisbal/.gem/ruby/2.4.0/gems/fastlane-2.89.0/fastlane/lib/fastlane/commands_generator.rb:333:in `run'
  /Users/chrisbal/.gem/ruby/2.4.0/gems/fastlane-2.89.0/fastlane/lib/fastlane/commands_generator.rb:42:in `start'
  /Users/chrisbal/.gem/ruby/2.4.0/gems/fastlane-2.89.0/fastlane/lib/fastlane/cli_tools_distributor.rb:107:in `take_off'
  /Users/chrisbal/.gem/ruby/2.4.0/gems/fastlane-2.89.0/bin/fastlane:20:in `<top (required)>'
  /Users/chrisbal/.gem/ruby/2.4.0/bin/fastlane:22:in `load'
  /Users/chrisbal/.gem/ruby/2.4.0/bin/fastlane:22:in `<top (required)>'
```

**Comment by nakiostudio** [comment]
Hi @chrisballinger  👋 

Thanks for reporting. This is due to a change on the xccovreport's format vs xccoverage's. I will hope to get a fix out soon.

**Comment by chrisballinger** [comment]
Thanks!
