### ISSUE TITLE
Failed to load command: xcov

### ISSUE THREAD

**Issue by ornithocoder** [nakiostudio/xcov#134]
Hi,

The project I work on uses Rake tasks to automate common tasks. For generating code coverage, the method is:

```ruby
def xcov(workspace:, scheme:, exclude_targets:, output_directory:)
    systemOrExit "bundle exec xcov \
            --workspace #{workspace} \
            --skip_slack \
            --configuration Debug \
            --scheme #{scheme} \
            --exclude_targets #{exclude_targets} \
            --html_report \
            --minimum_coverage_percentage 80 \
            --ignore_file_path .xcovignore \
            --output_directory #{output_directory} \
            --disable_coveralls \
            --verbose"
end
```

The method simply runs `xcov` using `bundler`.

When the report fails because it didn't reach the minimum coverage percentage, `xcov` fails suggestion to create a `fastlane/fastlane` issue.

```
+--------------------+--------+
|    xcov Coverage Report     |
+--------------------+--------+
|     Example.app    | 79.51% |
+--------------------+--------+

[15:22:15]: Actual Code Coverage (79.51%) below threshold of 80.00%
[15:22:15]: The build has been marked as failed because minimum overall coverage has not been reached.

Looking for related GitHub issues on fastlane/fastlane...

Found no similar issues. To create a new issue, please visit:
https://github.com/fastlane/fastlane/issues/new
Run `fastlane env` to append the fastlane environment to your issue
bundler: failed to load command: xcov (/Users/user/.rbenv/versions/2.2.5/bin/xcov)
RuntimeError: [!] Error creating your coverage report - see the log above
  /Users/user/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/xcov-1.4.3/lib/xcov/error_handler.rb:20:in `handle_error'
  /Users/user/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/xcov-1.4.3/lib/xcov/error_handler.rb:25:in `handle_error_with_custom_message'
  /Users/user/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/xcov-1.4.3/lib/xcov/manager.rb:130:in `validate_report'
  /Users/user/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/xcov-1.4.3/lib/xcov/manager.rb:32:in `run'
  /Users/user/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/xcov-1.4.3/lib/xcov/commands_generator.rb:41:in `block (2 levels) in run'
  /Users/user/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
  /Users/user/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
  /Users/user/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
  /Users/user/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
  /Users/user/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/fastlane-2.99.1/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:74:in `run!'
  /Users/user/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
  /Users/user/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/xcov-1.4.3/lib/xcov/commands_generator.rb:46:in `run'
  /Users/user/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/xcov-1.4.3/lib/xcov/commands_generator.rb:15:in `start'
  /Users/user/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/xcov-1.4.3/bin/xcov:6:in `<top (required)>'
  /Users/user/.rbenv/versions/2.2.5/bin/xcov:23:in `load'
  /Users/user/.rbenv/versions/2.2.5/bin/xcov:23:in `<top (required)>'
```

I would expect `bundle exec xcov` to exit with an error code, but without printing anything related to `fastlane`.

**Comment by quintuschen** [comment]
I have the same problem :(
