### ISSUE TITLE
xcov ruby 2.6.0 issue with %

### ISSUE THREAD

**Issue by HellGhost** [nakiostudio/xcov#145]
10:40:48 ArgumentError: [!] incomplete format specifier; use %% (double %) instead
10:40:48   /Users/jenkins/fastlane_gem/ruby/2.6.0/gems/xcov-1.5.0/lib/xcov/manager.rb:129:in `%'
10:40:48   /Users/jenkins/fastlane_gem/ruby/2.6.0/gems/xcov-1.5.0/lib/xcov/manager.rb:129:in `validate_report'
10:40:48   /Users/jenkins/fastlane_gem/ruby/2.6.0/gems/xcov-1.5.0/lib/xcov/manager.rb:32:in `run'
10:40:48   /Users/jenkins/fastlane_gem/ruby/2.6.0/gems/fastlane-2.116.0/fastlane/lib/fastlane/actions/xcov.rb:8:in `run'
10:40:48   /Users/jenkins/fastlane_gem/ruby/2.6.0/gems/fastlane-2.116.0/fastlane/lib/fastlane/runner.rb:253:in `block (2 levels) in execute_action'
10:40:48   /Users/jenkins/fastlane_gem/ruby/2.6.0/gems/fastlane-2.116.0/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
10:40:48   /Users/jenkins/fastlane_gem/ruby/2.6.0/gems/fastlane-2.116.0/fastlane/lib/fastlane/runner.rb:232:in `block in execute_action'
10:40:48   /Users/jenkins/fastlane_gem/ruby/2.6.0/gems/fastlane-2.116.0/fastlane/lib/fastlane/runner.rb:227:in `chdir'
10:40:48   /Users/jenkins/fastlane_gem/ruby/2.6.0/gems/fastlane-2.116.0/fastlane/lib/fastlane/runner.rb:227:in `execute_action'
10:40:48   /Users/jenkins/fastlane_gem/ruby/2.6.0/gems/fastlane-2.116.0/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
10:40:48   /Users/jenkins/fastlane_gem/ruby/2.6.0/gems/fastlane-2.116.0/fastlane/lib/fastlane/fast_file.rb:154:in `method_missing'
10:40:48   Fastfile:20:in `block in parsing_binding'
10:40:48   /Users/jenkins/fastlane_gem/ruby/2.6.0/gems/fastlane-2.116.0/fastlane/lib/fastlane/lane.rb:33:in `call'
10:40:48   /Users/jenkins/fastlane_gem/ruby/2.6.0/gems/fastlane-2.116.0/fastlane/lib/fastlane/runner.rb:204:in `try_switch_to_lane'
10:40:48   /Users/jenkins/fastlane_gem/ruby/2.6.0/gems/fastlane-2.116.0/fastlane/lib/fastlane/runner.rb:146:in `trigger_action_by_name'
10:40:48   /Users/jenkins/fastlane_gem/ruby/2.6.0/gems/fastlane-2.116.0/fastlane/lib/fastlane/fast_file.rb:154:in `method_missing'
10:40:48   Fastfile:49:in `block in parsing_binding'
10:40:48   /Users/jenkins/fastlane_gem/ruby/2.6.0/gems/fastlane-2.116.0/fastlane/lib/fastlane/lane.rb:33:in `call'
10:40:48   /Users/jenkins/fastlane_gem/ruby/2.6.0/gems/fastlane-2.116.0/fastlane/lib/fastlane/runner.rb:204:in `try_switch_to_lane'
10:40:48   /Users/jenkins/fastlane_gem/ruby/2.6.0/gems/fastlane-2.116.0/fastlane/lib/fastlane/runner.rb:146:in `trigger_action_by_name'
10:40:48   /Users/jenkins/fastlane_gem/ruby/2.6.0/gems/fastlane-2.116.0/fastlane/lib/fastlane/fast_file.rb:154:in `method_missing'
10:40:48   Fastfile:301:in `block (2 levels) in parsing_binding'
10:40:48   Fastfile:298:in `each'
10:40:48   Fastfile:298:in `block in parsing_binding'
10:40:48   /Users/jenkins/fastlane_gem/ruby/2.6.0/gems/fastlane-2.116.0/fastlane/lib/fastlane/lane.rb:33:in `call'
10:40:48   /Users/jenkins/fastlane_gem/ruby/2.6.0/gems/fastlane-2.116.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
10:40:48   /Users/jenkins/fastlane_gem/ruby/2.6.0/gems/fastlane-2.116.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
10:40:48   /Users/jenkins/fastlane_gem/ruby/2.6.0/gems/fastlane-2.116.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
10:40:48   /Users/jenkins/fastlane_gem/ruby/2.6.0/gems/fastlane-2.116.0/fastlane/lib/fastlane/lane_manager.rb:56:in `cruise_lane'
10:40:48   /Users/jenkins/fastlane_gem/ruby/2.6.0/gems/fastlane-2.116.0/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
10:40:48   /Users/jenkins/fastlane_gem/ruby/2.6.0/gems/fastlane-2.116.0/fastlane/lib/fastlane/commands_generator.rb:108:in `block (2 levels) in run'
10:40:48   /Users/jenkins/fastlane_gem/ruby/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
10:40:48   /Users/jenkins/fastlane_gem/ruby/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
10:40:48   /Users/jenkins/fastlane_gem/ruby/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
10:40:48   /Users/jenkins/fastlane_gem/ruby/2.6.0/gems/fastlane-2.116.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
10:40:48   /Users/jenkins/fastlane_gem/ruby/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
10:40:48   /Users/jenkins/fastlane_gem/ruby/2.6.0/gems/fastlane-2.116.0/fastlane/lib/fastlane/commands_generator.rb:333:in `run'
10:40:48   /Users/jenkins/fastlane_gem/ruby/2.6.0/gems/fastlane-2.116.0/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
10:40:48   /Users/jenkins/fastlane_gem/ruby/2.6.0/gems/fastlane-2.116.0/fastlane/lib/fastlane/cli_tools_distributor.rb:113:in `take_off'
10:40:48   /Users/jenkins/fastlane_gem/ruby/2.6.0/gems/fastlane-2.116.0/bin/fastlane:23:in `<top (required)>'
10:40:48   /Users/jenkins/fastlane_gem/ruby/2.6.0/bin/fastlane:23:in `load'
10:40:48   /Users/jenkins/fastlane_gem/ruby/2.6.0/bin/fastlane:23:in `<top (required)>'
10:40:49 Build step 'Execute shell' marked build as failure

**Comment by raafaelima** [comment]
Hi,

I'm having the same problem on my project, any news about it?

**Comment by iBotPeaches** [comment]
Sorry we never visited this. With Ruby 2.6 EOL, I believe this isn't worth triaging. Sorry.
